# Generated by cabinet' `just publish`. DO NOT EDIT.
cask "cabinet" do
  version "0.5.0"
  sha256 "b66810084f4659a5aff050447d7d4706d3a0b7779b706ada1ab916a4124b88bf"

  url "https://dl.dept.monster/cabinet/Cabinet_#{version}_aarch64.dmg"
  name "Cabinet"
  desc "Ministers of AI advisors and editors for organizational exercises"
  homepage "https://cabinet.monster"

  # arm64 only — CI builds a single aarch64-apple-darwin bundle.
  depends_on arch: :arm64
  # Big Sur is the floor by arithmetic, not by choice: tauri.conf.json sets no
  # minimumSystemVersion, and no earlier macOS ran on Apple Silicon.
  depends_on macos: :big_sur

  app "Cabinet.app"

  zap trash: [
    "~/Library/Application Support/Cabinet",
    "~/Library/Application Support/monster.cabinet",
    "~/Library/Caches/monster.cabinet",
    "~/Library/WebKit/monster.cabinet",
    "~/Library/Preferences/monster.cabinet.plist",
    "~/Library/Saved Application State/monster.cabinet.savedState",
  ]
end
