# Generated by cluster's `just publish`. DO NOT EDIT.
cask "cluster" do
  version "0.3.0"
  sha256 "d5eb43f78ed085fe85ad3466b86384130912a8a5a0ab85f01f523aee29e52bf6"

  url "https://dl.dept.monster/cluster/Cluster-#{version}.zip"
  name "Cluster Monster"
  desc "Research any subject: one curated claim corpus, three lenses"
  homepage "https://cluster.monster"

  # arm64 only — on-device inference is MLX/Metal on Apple Silicon.
  depends_on arch: :arm64
  depends_on macos: ">= :tahoe"

  app "Cluster.app"

  zap trash: [
    "~/Library/Application Support/Cluster",
    "~/Library/Preferences/monster.cluster.Cluster.plist",
  ]
end
