# Generated by cluster's `just publish`. DO NOT EDIT.
cask "cluster" do
  version "0.2.3"
  sha256 "77b3c275659ca3677b5c7bd6f2ac69a2df6650a3b3dd1a1c2d3ca061ab65093e"

  url "https://dl.dept.monster/cluster/Cluster-#{version}.zip"
  name "Cluster Monster"
  desc "Research any subject: one curated claim corpus, three lenses"
  homepage "https://cluster.monster"

  # arm64 only — on-device inference is MLX/Metal on Apple Silicon.
  depends_on arch: :arm64
  depends_on macos: ">= :tahoe"

  app "Cluster.app"

  zap trash: [
    "~/Library/Application Support/Cluster",
    "~/Library/Preferences/monster.cluster.Cluster.plist",
  ]
end
