# Generated by cluster's `just publish`. DO NOT EDIT.
cask "cluster" do
  version "0.2.0"
  sha256 "0c8d464f6206873d2fbfdbc7aa8efd0be5691f3cb82e20cf3abca8c4b917c7f7"

  url "https://dl.dept.monster/cluster/Cluster-#{version}.zip"
  name "Cluster Monster"
  desc "Research any subject: one curated claim corpus, three lenses"
  homepage "https://cluster.monster"

  # arm64 only — on-device inference is MLX/Metal on Apple Silicon.
  depends_on arch: :arm64
  depends_on macos: ">= :tahoe"

  app "Cluster.app"

  zap trash: [
    "~/Library/Application Support/Cluster",
    "~/Library/Preferences/monster.cluster.Cluster.plist",
  ]
end
