# Generated by metalbug's `just publish`. DO NOT EDIT.
cask "metalbug" do
  version "0.1.0"
  sha256 "19c3ab0c6d6b939eb6c0d1e5ac6fb9d84c8b5e077b616169f78fffada332e575"

  url "https://dl.dept.monster/metalbug/Metalbug-#{version}.zip"
  name "Metalbug"
  desc "Lightweight menu bar GPU monitor for Apple Silicon"
  homepage "https://metalbug.monster"

  # arm64 only — the app is built around AGX and unified memory.
  depends_on arch: :arm64
  depends_on macos: ">= :ventura"

  app "Metalbug.app"

  zap trash: [
    "~/Library/Preferences/com.rossturk.metalbug.plist",
  ]
end
