# Generated by metalbug's `just publish`. DO NOT EDIT.
cask "metalbug" do
  version "0.2.0"
  sha256 "3b41a69826ed47781387d61825e0634baf3cca7c6da2ad0875c2c93053f2b99b"

  url "https://dl.dept.monster/metalbug/Metalbug-#{version}.zip"
  name "Metalbug"
  desc "Lightweight menu bar GPU monitor for Apple Silicon"
  homepage "https://metalbug.monster"

  # arm64 only — the app is built around AGX and unified memory.
  depends_on arch: :arm64
  depends_on macos: :ventura

  app "Metalbug.app"

  zap trash: [
    "~/Library/Preferences/com.rossturk.metalbug.plist",
  ]
end
