# Generated by sanity's `just publish`. DO NOT EDIT.
cask "sanity" do
  version "0.15.0"
  sha256 "dc88c90d0128dd6c5ba0e43eea78a83aa9f9b28f4fde749e8aaa095ee9aecf3b"

  url "https://dl.dept.monster/sanity/Sanity_#{version}_aarch64.dmg"
  name "Sanity"
  desc "See where the thinking in your codebase actually is"
  homepage "https://sanity.monster"

  # arm64 only — CI builds a single aarch64-apple-darwin bundle.
  depends_on arch: :arm64
  # Big Sur is the floor by arithmetic, not by choice: tauri.conf.json sets no
  # minimumSystemVersion, and no earlier macOS ran on Apple Silicon.
  depends_on macos: :big_sur

  app "Sanity.app"
  binary "#{appdir}/Sanity.app/Contents/MacOS/sanity"

  zap trash: [
    "~/Library/Application Support/Sanity",
    "~/Library/WebKit/sanity",
    "~/Library/Preferences/monster.sanity.plist",
    "~/Library/Saved Application State/monster.sanity.savedState",
  ]
end
