# Generated by sanity's `just publish`. DO NOT EDIT.
cask "sanity" do
  version "0.5.1"
  sha256 "f6f37f5285aeb9edfacde532d7ab2f2d09f0fc0ff4fff6b2b1d88f924eaf88d8"

  url "https://dl.dept.monster/sanity/Sanity_#{version}_aarch64.dmg"
  name "Sanity"
  desc "See where the thinking in your codebase actually is"
  homepage "https://sanity.monster"

  # arm64 only — CI builds a single aarch64-apple-darwin bundle.
  depends_on arch: :arm64
  # Big Sur is the floor by arithmetic, not by choice: tauri.conf.json sets no
  # minimumSystemVersion, and no earlier macOS ran on Apple Silicon.
  depends_on macos: :big_sur

  app "Sanity.app"

  zap trash: [
    "~/Library/Application Support/Sanity",
    "~/Library/WebKit/sanity",
    "~/Library/Preferences/monster.sanity.plist",
    "~/Library/Saved Application State/monster.sanity.savedState",
  ]
end
