# Generated by sewcrates' `just publish`. DO NOT EDIT.
cask "sewcrates" do
  version "0.2.2"
  sha256 "984de19cd074555d1453338ce56a0a49360a2d96f8d90422f77e249d0577e2b8"

  url "https://dl.dept.monster/sewcrates/Sewcrates_#{version}_aarch64.dmg"
  name "Sewcrates"
  desc "Cabinet of AI advisors and editors for organizational exercises"
  homepage "https://sewcrates.monster"

  # arm64 only — CI builds a single aarch64-apple-darwin bundle.
  depends_on arch: :arm64
  # Big Sur is the floor by arithmetic, not by choice: tauri.conf.json sets no
  # minimumSystemVersion, and no earlier macOS ran on Apple Silicon.
  depends_on macos: :big_sur

  app "Sewcrates.app"

  zap trash: [
    "~/Library/Application Support/Sewcrates",
    "~/Library/Application Support/monster.sewcrates",
    "~/Library/Caches/monster.sewcrates",
    "~/Library/WebKit/monster.sewcrates",
    "~/Library/Preferences/monster.sewcrates.plist",
    "~/Library/Saved Application State/monster.sewcrates.savedState",
  ]
end
