# Generated by tally's `just publish`. DO NOT EDIT.
cask "tally" do
  version "0.4.0"
  sha256 "71785144683ad7f87854aa96b6a0b7e27be5ca49e47d783dab5f16b58a33ce39"

  url "https://dl.dept.monster/tally/Tally_#{version}_aarch64.dmg"
  name "Tally"
  desc "Local-first metrics: collectors gather numbers, agents build dashboards"
  homepage "https://tally.monster"

  # arm64 only — CI builds a single aarch64-apple-darwin bundle.
  depends_on arch: :arm64
  # Big Sur is the floor by arithmetic, not by choice: tauri.conf.json sets no
  # minimumSystemVersion, and no earlier macOS ran on Apple Silicon.
  depends_on macos: :big_sur

  app "Tally.app"

  zap trash: [
    "~/Library/Application Support/Tally",
    "~/Library/WebKit/tally",
    "~/Library/Preferences/monster.tally.plist",
    "~/Library/Saved Application State/monster.tally.savedState",
  ]
end
