# Generated by tattle's `just publish`. DO NOT EDIT.
cask "tattle" do
  version "0.2.0"
  sha256 "d7f74852da394aac37598191fd118d8f729d3da5b804b0a8515348c5782660e0"

  url "https://dl.dept.monster/tattle/Tattle_#{version}_aarch64.dmg"
  name "Tattle"
  desc "Cast a question across the field of LLMs and map how it sees a topic"
  homepage "https://tattle.monster"

  # arm64 only — CI builds a single aarch64-apple-darwin bundle.
  depends_on arch: :arm64
  # Big Sur is the floor by arithmetic, not by choice: tauri.conf.json sets no
  # minimumSystemVersion, and no earlier macOS ran on Apple Silicon.
  depends_on macos: :big_sur

  app "Tattle.app"

  zap trash: [
    "~/Library/Application Support/Tattle",
    "~/Library/WebKit/dev.rossturk.tattle",
    "~/Library/Preferences/dev.rossturk.tattle.plist",
    "~/Library/Saved Application State/dev.rossturk.tattle.savedState",
  ]
end
