# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krapow < Formula
  desc "Run GitHub Actions self-hosted runners as Incus or Tart VMs"
  homepage "https://github.com/widdlab/krapow"
  version "0.2.0"
  license "Apache-2.0"

  depends_on "cirruslabs/cli/tart" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/widdlab/krapow/releases/download/v0.2.0/krapow_0.2.0_darwin_amd64.tar.gz"
      sha256 "534130c53ccb1d5e36a3a6be7f680a0bd81ae39eb0fb0c57f21f6f1918045ec2"

      define_method(:install) do
        bin.install "krapow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/widdlab/krapow/releases/download/v0.2.0/krapow_0.2.0_darwin_arm64.tar.gz"
      sha256 "33315fc32b13fc4032efa14eda95b920a048c59bb30778352f88f25669d84935"

      define_method(:install) do
        bin.install "krapow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/widdlab/krapow/releases/download/v0.2.0/krapow_0.2.0_linux_amd64.tar.gz"
      sha256 "c3c3e6dbcd18b1f8fbb2e21f625b28da6e76de81e18f523883561e9f5b599afa"
      define_method(:install) do
        bin.install "krapow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/widdlab/krapow/releases/download/v0.2.0/krapow_0.2.0_linux_arm64.tar.gz"
      sha256 "8dac375767e6ae9056d95390d6aaa40910d69e721c9db8ecb51922cd40f0dc0f"
      define_method(:install) do
        bin.install "krapow"
      end
    end
  end

  test do
    system "#{bin}/krapow", "doctor"
  end
end
