# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krapow < Formula
  desc "Run GitHub Actions self-hosted runners as Incus or Tart VMs"
  homepage "https://github.com/monsterdept/krapow"
  version "0.4.1"
  license "Apache-2.0"

  depends_on "cirruslabs/cli/tart" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monsterdept/krapow/releases/download/v0.4.1/krapow_0.4.1_darwin_amd64.tar.gz"
      sha256 "cef51b1422a33c14f1cd88feab49988de0fe0e8c7bb4016ea5ceaaf4e0489e12"

      define_method(:install) do
        bin.install "krapow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monsterdept/krapow/releases/download/v0.4.1/krapow_0.4.1_darwin_arm64.tar.gz"
      sha256 "ed92f949bc627057d9876d41d97176ce01b80b46a8d81d5db970f690c02e0ad8"

      define_method(:install) do
        bin.install "krapow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/monsterdept/krapow/releases/download/v0.4.1/krapow_0.4.1_linux_amd64.tar.gz"
      sha256 "2dfba7bf058e155cff916a158b9832251df1a48c8911c74c84e1097e08983b2d"
      define_method(:install) do
        bin.install "krapow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monsterdept/krapow/releases/download/v0.4.1/krapow_0.4.1_linux_arm64.tar.gz"
      sha256 "aedb02637047bcec17889b53586f54158fb03f6aba43463db3607b4ededc4c4b"
      define_method(:install) do
        bin.install "krapow"
      end
    end
  end

  test do
    system "#{bin}/krapow", "doctor"
  end
end
