# typed: false
# frozen_string_literal: true

# Generated by reportcard's `just publish`. DO NOT EDIT.
class Reportcard < Formula
  desc "Turn your GitHub history into an annotated data story"
  homepage "https://github.com/monsterdept/reportcard"
  version "0.3.0"
  license "Apache-2.0"

  # The web UI is compiled into the binary; gh is what reads GitHub, including
  # your private repositories, using the login you already have.
  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.dept.monster/reportcard/reportcard_0.3.0_darwin_amd64.tar.gz"
      sha256 "aaed34e943027340c419d24a46c3cdca3df275fba238c91d5f2d33d24496df9a"
    end
    if Hardware::CPU.arm?
      url "https://dl.dept.monster/reportcard/reportcard_0.3.0_darwin_arm64.tar.gz"
      sha256 "6e6751f0eba3dd61c3da5d6ebe3557f2d155a4354953565bbea56bd7b9b98487"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/reportcard/reportcard_0.3.0_linux_amd64.tar.gz"
      sha256 "c41233236c2283fed9020c2e2567ed8f7006b3d3df23795a9c51fd374af5fc17"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/reportcard/reportcard_0.3.0_linux_arm64.tar.gz"
      sha256 "93ee38bce60bf95e4efc6690544a90a8a37268383a9ff5224a79be2cdf3ba9a0"
    end
  end

  def install
    bin.install "reportcard"
  end

  # Exercises the real thing rather than --version: doctor inspects the machine
  # and the current directory. Run in a scratch dir with no workspace it must
  # still exit 0, reporting what it found — that is the documented contract.
  test do
    output = shell_output("#{bin}/reportcard doctor")
    assert_match "workspace", output
    assert_match "reportcard", output
  end
end
