# typed: false
# frozen_string_literal: true

# Generated by reportcard's `just publish`. DO NOT EDIT.
class Reportcard < Formula
  desc "Turn your GitHub history into an annotated data story"
  homepage "https://github.com/monsterdept/reportcard"
  version "0.2.0"
  license "Apache-2.0"

  # The web UI is compiled into the binary; gh is what reads GitHub, including
  # your private repositories, using the login you already have.
  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.dept.monster/reportcard/reportcard_0.2.0_darwin_amd64.tar.gz"
      sha256 "c65ef374ff240d384d3df76321e30c75a857ace15e4cbe7dc7162bb070a9b5e2"
    end
    if Hardware::CPU.arm?
      url "https://dl.dept.monster/reportcard/reportcard_0.2.0_darwin_arm64.tar.gz"
      sha256 "53de322432ce311ba69c9a073e19e73a173960471992eb8b551ea28258380fd7"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/reportcard/reportcard_0.2.0_linux_amd64.tar.gz"
      sha256 "42d26f10fa97d7a24d594539af30652d324069ea4f30655605d5c617bcbd9588"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/reportcard/reportcard_0.2.0_linux_arm64.tar.gz"
      sha256 "04b4daab80dc1fab44b64e2a237029f524b4c2275db6fb517429feab6d5847c2"
    end
  end

  def install
    bin.install "reportcard"
  end

  # Exercises the real thing rather than --version: doctor inspects the machine
  # and the current directory. Run in a scratch dir with no workspace it must
  # still exit 0, reporting what it found — that is the documented contract.
  test do
    output = shell_output("#{bin}/reportcard doctor")
    assert_match "workspace", output
    assert_match "reportcard", output
  end
end
