# typed: false
# frozen_string_literal: true

# Generated by reportcard's `just publish`. DO NOT EDIT.
class Reportcard < Formula
  desc "Turn your GitHub history into an annotated data story"
  homepage "https://github.com/monsterdept/reportcard"
  version "0.4.1"
  license "Apache-2.0"

  # The web UI is compiled into the binary; gh is what reads GitHub, including
  # your private repositories, using the login you already have.
  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.dept.monster/reportcard/reportcard_0.4.1_darwin_amd64.tar.gz"
      sha256 "b80fd24539cb7eb91957500107a28a30ef31f938fc7db94c5d23552ffacebe42"
    end
    if Hardware::CPU.arm?
      url "https://dl.dept.monster/reportcard/reportcard_0.4.1_darwin_arm64.tar.gz"
      sha256 "31aa345ccdb59c87265f381c599cb0df7af0130f66f9e75a0d351dc6ef0cb922"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/reportcard/reportcard_0.4.1_linux_amd64.tar.gz"
      sha256 "053024c57dc894f38e2001a62b200f73d0198e7092878338237ed7deb798abca"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/reportcard/reportcard_0.4.1_linux_arm64.tar.gz"
      sha256 "84d811bd1a9507536d78ec18c59ac21acbce3ec9dda92e65874493a38a00041a"
    end
  end

  def install
    bin.install "reportcard"
  end

  # Exercises the real thing rather than --version: doctor inspects the machine
  # and the current directory. Run in a scratch dir with no workspace it must
  # still exit 0, reporting what it found — that is the documented contract.
  test do
    output = shell_output("#{bin}/reportcard doctor")
    assert_match "workspace", output
    assert_match "reportcard", output
  end
end
