# typed: false
# frozen_string_literal: true

# Generated by whatson's `just publish`. DO NOT EDIT.
class Whatson < Formula
  desc "Find out what is listening on a TCP port, fast"
  homepage "https://github.com/monsterdept/whatson"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.dept.monster/whatson/whatson_0.1.0_darwin_amd64.tar.gz"
      sha256 "fef50d84695ebbcefae90b3db948f5358127c00e209ecde3ca5382e90e412d46"
    end
    if Hardware::CPU.arm?
      url "https://dl.dept.monster/whatson/whatson_0.1.0_darwin_arm64.tar.gz"
      sha256 "4b73926688202d7609eaa580cb864c08799d7145365cf2627e6f7834d91477e0"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/whatson/whatson_0.1.0_linux_amd64.tar.gz"
      sha256 "592e29af077e0575a05ef92e9ad0f87742f389401cbeef02730d035c55deb616"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.dept.monster/whatson/whatson_0.1.0_linux_arm64.tar.gz"
      sha256 "2268da5a8f9dd55ee3fcaa92f99d3f8cb8506ebdc1d2f6d81a9c4aaeba5269c0"
    end
  end

  def install
    bin.install "whatson"
  end

  # Exercises the real scan path rather than just --version. Port 1 is never
  # listening, so whatson reports that and exits 1 — the documented contract.
  test do
    assert_match "nothing listening", shell_output("#{bin}/whatson 1 2>&1", 1)
  end
end
